export {default as Navbar} from './Navbar.jsx'
export {default as Leftbar} from './Leftbar.jsx'
export {default as Rightbar} from './Rightbar.jsx'
export {default as Main} from './Main.jsx'
export {default as Chart} from './Chart.jsx'
export {default as Widgets} from './Widgets.jsx'
export {default as RevenueComponent} from './RevenueComponent.jsx'
export {default as LatestTransactions} from './LatestTransactions.jsx' //Edit
export {default as LatestOrders} from './LatestOrders.jsx'
export {default as UsersTable} from './UsersTable.jsx'